//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class experiencia
    {
        public string puesto { get; set; }
        public string lugar { get; set; }
        public string detalles { get; set; }
        public int id { get; set; }
    }
}
